Repository oss2025hnu/reposcore-py, pull requests merged in 2025-05, with the labels that each got.

#641 [DOC] 디버깅 및 로깅 가이드를 readme.md에 링크 연결 PR
  README.md
  template_README.md
Labels: documentation

#721 [BUG] make readme 시 불필요한 fontManager 로그 출력됨
  reposcore/output_handler.py
Labels: bug

#737 overall_repository 저장소별 기여도 txt파일도 표 형태로 출력 요청
  reposcore/__main__.py
Labels: enhancement

#738 의존성 관리 가이드 설명 추가
  README.md
  docs/dependency_guide.md
  template_README.md
Labels: enhancement

#748 py저장소의 메인모듈 설명 추가
  template_README.md
Labels: documentation

#754 [BUG] 동점자 순위처리 안 됨 #744 에 대한 pr입니다.
  reposcore/analyzer.py
  reposcore/output_handler.py
Labels: bug

#805 [BUG] 하위권 user 의 점수가 js와 py 점수 차이에 대한 PR
  reposcore/analyzer.py
  tests/test_analyzer.py
Labels: bug

#804 [DOC] README에서 중복된 결과 파일 설명 정리 에 대한 pr입니다.
  README.md
  template_README.md
Labels: documentation
