Repository oss2025hnu/reposcore-py, pull requests merged in 2025-04, with the labels that each got.

#263 --repo 입력 검증 및 저장소 존재 여부 확인 기능 추가 PR
  reposcore/__main__.py
Labels: enhancement

#276 [STYLE] --help 메시지 개선
  README.md
  reposcore/__main__.py
Labels: enhancement

#280 [FIX] --output 옵션이 출력 디렉토리에 제대로 반영되지 않던 문제 수정
  README.md
  reposcore/__main__.py
  reposcore/analyzer.py
Labels: bug

#281 [DOC] Score Formula 단순화 (기능과 버그 관련 변수를 통합) 에 대한 PR
  README.md
Labels: documentation

#282 [FEAT] collect_issues를 collect_PRs 와 통합
  reposcore/__main__.py
  reposcore/analyzer.py
Labels: enhancement

#283 [STYLE] 오타 수정
  README.md
  reposcore/__main__.py
  reposcore/analyzer.py
Labels: documentation

#288 [REFACTOR] collect_PRs_and_issues 함수를 개선해주세요. - collect_PRs_and_issues 함수 개선
  reposcore/analyzer.py
Labels: enhancement

#291 Makefile에 pip로 라이브러리 설치 자동화
  Makefile
  README.md
  requirements-dev.txt
  requirements.txt
Labels: enhancement

#296 [REFACTOR] 결과물로 출력되는 chart.png 가독성 향상에 대한 PR
  reposcore/analyzer.py
Labels: enhancement

#294 [BUG] 'link'에러로 종료되는 버그가 발생. 에 대한 PR
  reposcore/analyzer.py
Labels: bug

#300 [TEST] calculate_scores 함수에 대한 예제 테스트 추가
  tests/test_analyzer.py
  tests/test_main.py
Labels: enhancement

#315 #297 [FEAT] README의 Usage 자동 동기화(--help 출력 결과 반영)
  Makefile
  scripts/generate_readme.py
  template_README.md
Labels: enhancement

#338 [DOC] 프로젝트 작성 시 주의사항 별도의 문서로 옮기기
  README.md
  docs/project_guidelines.md
  template_README.md
Labels: documentation

#361 [DOC] 프로젝트 주의사항 항목추가
  docs/project_guidelines.md
Labels: documentation

#355 docs/images/token-apply.png파일 누락수정
  docs/github-token-guide.md
Labels: documentation

#388 README.md의 usage부분 불필요 코드 제거
  README.md
Labels: documentation

#400 [BUG] --format 옵션 설명에 잘못된 예시값 PR
  reposcore/__main__.py
Labels: bug

#434 [DOC] 채점 공식 수정: 기능/버그 PR 0건 시 문서 PR 최대 3건 인정되도록 P_valid 수정
  reposcore/analyzer.py
Labels: enhancement

#436 test_user2 의 결과값 수정
  tests/test_analyzer.py
Labels: bug

#451 [DOC] 채점 공식 수정: 기능/버그 PR 0건 시 문서 PR 최대 3건 인정되도록 P_valid 수정 에대한 readme 수정
  README.md
  template_README.md
Labels: documentation

#453 한국 시간대 설정 가이드 추가
  README.md
  docs/korean-timezone-guide.md
  template_README.md
Labels: documentation

#463 [FIX] test_main_without_repo_option 함수의 에러 메시지 포함 조견 변경
  tests/test_main.py
Labels: bug

#465 excluded_ids 추가 PR
  reposcore/analyzer.py
Labels: enhancement

#478 [DOC] readme.md(template_README.md)오탈자 수정
  README.md
  template_README.md
Labels: typo

#504 [STYLE] 들여쓰기 수정
  reposcore/utils/validators.py
Labels: bug

#506 [BUG] 차트 이미지가 생성되지 않음 에 대한 PR
  reposcore/__main__.py
  reposcore/analyzer.py
Labels: bug

#522 [REFACTOR] 중복된 문자열을 상수로 리팩토링
  reposcore/__main__.py
Labels: enhancement

#576 [REFACTOR] 테스트 코드에서 RepoAnalyzer가 더미 저장소에 대한 예외적 동작을 할 수 있도록 코드 정리 필요에 대한 PR (#574)
  reposcore/__main__.py
  reposcore/analyzer.py
  reposcore/utils/github_utils.py
Labels: enhancement

#597 [REFACTOR] 잘못된 오류 메시지 변경에 대한 PR
  reposcore/analyzer.py
Labels: documentation

#633 [DOC] 오타수정
  docs/korean-timezone-guide.md
Labels: typo
